default_context:
  project_name: 'Mealer'
  project_slug: 'mealer'
  domain_main: 'mealer.com'
  domain_staging: 'stag.mealer.com'
  docker_swarm_stack_name_main: 'mealer-com'
  docker_swarm_stack_name_staging: 'stag-mealer-com'
  secret_key: '1e4b40d4f3ead5b85d14037e999c0063bebb88c11e59a7141477bbe539b424f0'
  first_superuser: 'admin@mealer.com'
  first_superuser_password: 'a445c27681293cc40c98629dfd3a612d19b2b090476806d1a2e316b3a548210c'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.mealer.com", "https://stag.mealer.com", "https://mealer.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@mealer.com'
  postgres_password: '5f24979fe84141b62812e02f18d17c49044aafded1e9321604d862e949974b2e'
  pgadmin_default_user: 'admin@mealer.com'
  pgadmin_default_user_password: 'a445c27681293cc40c98629dfd3a612d19b2b090476806d1a2e316b3a548210c'
  traefik_constraint_tag: 'mealer.com'
  traefik_constraint_tag_staging: 'stag.mealer.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:a445c27681293cc40c98629dfd3a612d19b2b090476806d1a2e316b3a548210c'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
